### ISSUE TITLE
mcrypt-extension is deprecated 

### ISSUE THREAD

**Issue by crynale** [BrianHenryIE/bh-wp-bitcoin-gateway#1]
The mcrypt extension has been abandonware for nearly a decade now, and was also fairly complex to use. It has therefore been deprecated in favour of OpenSSL, where it will be removed from the core and into PECL in PHP 7.2. Is there any solution for this problem?
Thanks

**Comment by Nullcorps** [comment]
as far as I recall the mcrypt bit was a requirement of the bitwasp library which was used to do all the address generation bit, and whilst, yes it's annoying, idk about you but I don't know how to change that. This request may be better directed at the bit-wasp folks, which i believe is here: https://github.com/Bit-Wasp/bitcoin-php

Perhaps there's a way to fork bitwasp and shift whatever they use mcrypt for to some other more modern library.. but tbh implementing that is probably a bit (a lot) above my skill level.

**Comment by crynale** [comment]
Thank you, I submit the request to the repository, such a level of programming is also far beyond my capabilities
