### ISSUE TITLE
Getting a weird Error

### ISSUE THREAD

**Issue by BrowserApi** [BrianHenryIE/bh-wp-bitcoin-gateway#2]
Hi, i installed the plugin on my localhost new wordpress website. Im getting an error
(Getting the same error even after enabled 'php GMP extension' )

ERROR:
```
Warning: preg_match(): Unknown modifier 'w' in E:\LARAGON\laragon\www\wpshop\wp-content\plugins\bh-wc-bitcoin-gateway\vendor-prefixed\brianhenryie\bh-wp-logger\src\api\class-api.php on line 326



Warning: session_start(): Session cannot be started after headers have already been sent in E:\LARAGON\laragon\www\wpshop\wp-content\plugins\woostify-sites-library\class-woostify-sites.php on line 2543


```
The line 326 error is showing like a loop, like showing the same error in continuous 99 lines

**Comment by BrowserApi** [comment]
I noticed the same error is mainly showing in few pages like:

1) Woocommerce plugin SETTINGS page
2) Order Placed Page

     rarely in some other pages too
---------------------------------------------
![ERROR 123](https://user-images.githubusercontent.com/107455731/218162233-86581001-5bf6-4a5f-ba8b-f03837653771.png)

**Comment by BrianHenryIE** [comment]
Thanks.

Try this: https://github.com/BrianHenryIE/bh-wc-bitcoin-gateway/releases/tag/2.0.0-b4

The error is in the logging library I wrote, and I think it's because I didn't escape the filepath before using it in a regex.

Let me know how that works, please.
